MascWebCore/urls.py
from django.urls import path, include  # add this
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("modules.home.urls")),
    path('labs/',include("modules.MascLab.urls")),
    path('engine/',include("modules.MascEngine.urls")),
    path('auth/',include("modules.UserAuthentication.urls")),
    path('profile/',include("modules.UserProfile.urls")),
    path('properties/', include("modules.CipherManager.urls")),
    path('plugins/', include("modules.plugins.urls")),
    path('toolprofile/', include("modules.toolprofile.urls"))
]

modules/MascEngine/urls.py
from django.urls import path, re_path
from modules.MascEngine import views

app_name = "MascEngine"

urlpatterns = [
    path('', views.index, name='MascEngine'),
    path('history', views.runMASCEngine, name='MASCEngine'),
    path('deleteCode/<int:id>/<str:name>', views.delete_source_code, name='deleteCode'),
    path('download/<str:app_name>', views.download, name='download')
]

modules/MascLab/urls.py
from django.urls import path, re_path
from modules.MascLab import views

urlpatterns = [
    path('', views.index, name='MascLab'),
    path('inputForm', views.input_Form, name='InputForm'),
    path('setup', views.set_up, name='setup')
]

modules/home/urls.py
from django.urls import path, re_path
from modules.home import views

urlpatterns = [
    path('', views.index, name='home'),
    path('about', views.about, name='about')
]

modules/plugins/urls.py
from django.urls import path, re_path
from modules.plugins import views

urlpatterns = [
    path('', views.index, name='plugins'),
    path('upload/', views.uploadPlugins, name='uploadPropertyForm'),
    path('delete/<int:id>', views.delete_plugin, name='delete'),
    path('compile/<int:id>', views.compile_class, name='compile'),
    path('status/<int:id>', views.update_status, name='status'),
]

modules/CipherManager/models.py
from django.db import models

class PropertiesList(models.Model):
    name = models.CharField(max_length=200)
    filename = models.CharField(max_length=100, db_index=True, default="any.properties")
    path = models.CharField(max_length=500)
    type = models.CharField(max_length=50)

# Create your models here.

modules/MascEngine/models.py
from datetime import datetime

from django.db import models


# Create your models here.
class ProcessLog(models.Model):
    properties = models.CharField(max_length=500)
    scope = models.CharField(max_length=50)
    status = models.CharField(max_length=20)
    source_code = models.ForeignKey('SourceCode', on_delete=models.CASCADE)
    start_time = models.DateTimeField(default=datetime.now())


class SourceCode(models.Model):
    zip_file_name = models.CharField(max_length=100, db_index=True)
    zip_file_directory = models.CharField(max_length=100, db_index=True)
    input_path = models.CharField(max_length=500)
    output_path = models.CharField(max_length=500)
    appName = models.CharField(max_length=50, unique=True)

modules/plugins/models.py
from django.db import models

# Create your models here.
class PluginsList(models.Model):
    name = models.CharField(max_length=200)
    filename = models.CharField(max_length=100, db_index=True, default="any.properties")
    compilation = models.CharField(max_length=200, default='false')
    classfile = models.CharField(max_length=200, default='any.class')
    status = models.CharField(max_length=200, default='active')
    path = models.CharField(max_length=500)

modules/toolprofile/models.py
from django.db import models

# Create your models here.

modules/CipherManager/views.py
import json
import os
from django.shortcuts import render
from modules.CipherManager.models import PropertiesList
from django.shortcuts import render, redirect
from django.http import HttpResponse

def index(request):
    uploaded_files_header = ["Id", "Name", "File Name", "Path", "Type", "Actions"]
    records = PropertiesList.objects.all().values()
    return render(request, "CipherManager/index.html", {
        "uploaded_files_header": uploaded_files_header,
        "records": records
    })


def editProperties(request, id):
    record = PropertiesList.objects.get(id=id)
    if request.method == "POST":
        filename = record.filename
        file_content = request.POST["content"]
        update_file_content(filename,file_content)
        return redirect(index)
        # edit requested
    property_name = record.name
    property_filename = record.filename
    property_operator = record.type
    content = read_data_from_uploaded_file(property_filename)
    return render(request, "CipherManager/edit.html", {
        "name" : property_name,
        "filename": property_filename,
        "type": property_operator,
        "content" : content
    })


def read_data_from_uploaded_file(f):
    with open('./modules/static/properties/'+f, 'r') as destination:
        contents = destination.read()
    return contents


def update_file_content(filename, content):
    arr = bytes(content, 'utf-8')
    with open('./modules/static/properties/'+filename, 'wb') as destination:
        destination.write(arr)


def handle_uploaded_file(f):
    with open('./modules/static/properties/'+f.name, 'wb') as destination:
        for chunk in f.chunks():
            destination.write(chunk)
    return destination.name


def delete_uploaded_file(f):
    path = './modules/static/properties/'+f
    if os.path.isfile(path):
        os.remove(path)

def uploadPropertyForm(request):
    if request.method == 'POST':
        name = request.POST['name']
        ptype = request.POST['type']
        print(ptype)
        filename = request.FILES['file'].name
        path = handle_uploaded_file(request.FILES['file']) # path from masc core shall be added
        data = PropertiesList(name = name,type = ptype, filename = filename, path = path);
        data.save()
        return render(request,'CipherManager/thanks.html')
    list_of_operators = ["StringOperator","ByteOperator", "InterprocOperator", "Flexible", "IntOperator"]
    return render(request, "CipherManager/uploadProperty.html", {
        "list_of_operators": list_of_operators
    })
# Create your views here.


def deleteProperties(request,id):
    record = PropertiesList.objects.get(id=id)
    delete_uploaded_file(record.filename)
    PropertiesList.objects.get(id=id).delete()
    return redirect(index)

modules/MascEngine/views.py
import sys
import os
from asgiref.sync import sync_to_async
from django.http import HttpResponse
from django.shortcuts import render

from modules.CipherManager.models import PropertiesList
from modules.MascEngine.models import SourceCode
from modules.MascEngine.models import ProcessLog
from zipfile import ZipFile
from datetime import datetime
import asyncio
from shutil import make_archive
from wsgiref.util import FileWrapper
from django.conf import settings
import time

# Create your views here.

import threading

class thread(threading.Thread):
    def __init__(self, app_name, build_properties_path,log_id):
        threading.Thread.__init__(self)
        self.app_name = app_name
        self.build_properties_path = build_properties_path
        self.log_id = log_id
        # helper function to execute the threads

    def run(self):
        print(str(self.app_name) + " " + str(self.build_properties_path))
        jar_path = settings.CORE_DIR + '/modules/static/properties/app-all.jar'
        p, status_code = asyncio.run(
            run('java -jar '+jar_path+' ' + self.build_properties_path))
        record =ProcessLog.objects.get(id=self.log_id)
        print('Hello =>'+record.status)
        print(settings.BASE_DIR)
        print(settings.CORE_DIR)
        if status_code == 0:
            record.status = 'completed'
        else:
            record.status = 'failed'
        record.save()
        sys.exit()
        print(self.is_alive)

async def run(cmd):
    print(cmd)
    proc = await asyncio.create_subprocess_shell(
        cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE)
    stdout, stderr = await proc.communicate()
    print(await proc.communicate())
    print(f'[{cmd!r} exited with {proc.returncode}]')
    utf = 'utf-8'
    status = 'ignore'
    if stdout:
        print(f'[stdout]\n{stdout.decode(utf,status)}')
        return stdout.decode(utf,status), proc.returncode
    if stderr:
        print(f'[stderr]\n{stderr.decode(utf,status)}')
        return stderr.decode(utf,status), proc.returncode


def read_selected_file(f):
    with open('./modules/static/properties/' + f, 'r') as destination:
        item = destination.read().split("\n")
    content = ''
    for line in item:
        if 'scope' in line.lower() or 'appsrc' in line.lower() or 'outputdir' in line.lower() or 'appname' in line.lower():
            continue
        else:
            content = content + line + '\n'
    return content


def handle_uploaded_file(f, app_name):
    with open('./modules/static/sourcecodes/' + f.name, 'wb') as destination:
        for chunk in f.chunks():
            destination.write(chunk)
    with ZipFile('./modules/static/sourcecodes/' + f.name, 'r') as zipObj:
        zipObj.extractall('./modules/static/unzippedCodes/' + app_name)
    inputPath = './modules/static/unzippedCodes/' + app_name
    data = SourceCode(zip_file_name=f.name, zip_file_directory='./modules/static/sourcecodes/' + f.name,
                      input_path=inputPath, output_path='', appName=app_name);
    data.save()
    return data.id, inputPath


async def build_properties(app_name, scope, input_path, contents):
    initial = 'appName=' + app_name + '\n' + 'scope=' + scope + '\n' + 'appSrc=' + input_path + '\n' + 'outputDir=./app/outputs/'+app_name+'\n'
    contents = initial + contents
    with open('./modules/static/properties/' + app_name + '.properties', 'w') as destination:
        destination.write(contents)
    return './modules/static/properties/' + app_name + '.properties'


def run_sub_process_masc_engine(build_properties_path, source_code_id, scope):
    source = SourceCode.objects.get(id=source_code_id)
    data = ProcessLog(properties=build_properties_path, scope=scope, status='running', source_code=source, start_time=datetime.now())
    data.save()
    threadMASC = thread(source.appName,build_properties_path,data.id)
    threadMASC.start()


def runMASCEngine(request):
    custome_operator_headers = ["Id", "Scope", "Properties", "App Name","Status","Actions"]
    if request.method == 'POST':
        scopes = request.POST['scope']
        properties_file = request.POST['file_name']
        app_name = request.POST['appName']
        contents = request.POST['content']
        source_code_id, input_path = handle_uploaded_file(request.FILES['sourcecode'], app_name)
        build_properties_path = asyncio.run(build_properties(app_name, scopes, input_path, contents))
        run_sub_process_masc_engine(build_properties_path,source_code_id,scopes)
    data = ProcessLog.objects.all().values()
    records = []
    for x in data:
        source = SourceCode.objects.get(id=x['source_code_id'])
        x['source_code'] = source
        arr = x['properties'].split('/')
        x['properties_name'] = arr[len(arr)-1]
        records.append(x)
    return render(request, "masc-engine/history.html", {
        "custome_operator_headers": custome_operator_headers,
        "records": records
    })


def index(request):
    if request.method == 'POST':
        scope = request.POST['scopes']
        properties = request.POST['properties']
        contents = read_selected_file(properties)
        return render(request, "masc-engine/engine-details.html", {
            "scope": scope,
            "filename": properties,
            "content": contents,
        })
    scopes = ['SELECTIVE', 'EXHAUSTIVE']
    records = PropertiesList.objects.all().values()
    return render(request, "masc-engine/engine.html", {
        "scopes": scopes,
        "properties_file": records
    })


def delete_uploaded_file(f):
    path = './app/outputs/'+f
    if os.path.isdir(path):
        os.system("rm -rf "+path)
    if os.path.isfile('./app/outputs/'+f+'./zip'):
        os.remove('./app/outputs/'+f+'./zip')


def delete_source_code(request,id,name):
    SourceCode.objects.get(id=id).delete()
    delete_uploaded_file(name)
    data = ProcessLog.objects.all().values()
    records = []
    for x in data:
        source = SourceCode.objects.get(id=x['source_code_id'])
        x['source_code'] = source
        arr = x['properties'].split('/')
        x['properties_name'] = arr[len(arr) - 1]
        records.append(x)
    custome_operator_headers = ["Id", "Scope", "Properties", "App Name","Status","Actions"]
    return render(request, "masc-engine/history.html", {
        "custome_operator_headers": custome_operator_headers,
        "records": records
    })


def download(request, app_name):
    files_path = "./app/outputs/"+app_name
    path_to_zip = make_archive(files_path, "zip", files_path)
    response = HttpResponse(FileWrapper(open(path_to_zip,'rb')), content_type='application/zip')
    response['Content-Disposition'] = 'attachment; filename="{filename}.zip"'.format(
        filename = app_name.replace(" ", "_")
    )
    return response
# Create your views here.

modules/UserAuthentication/views.py
import re
from django.shortcuts import render

# Create your views here.
def login(request):
    return render(request, "Authentication/login.html")

def register(request):
    return render(request, "Authentication/register.html")

modules/UserProfile/views.py
import profile
from urllib import request
from django.shortcuts import render

# Create your views here.
def profile(request):
    return render(request,"profile/profile.html")

modules/home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "home.html")

def about(request):
    return render(request, "about.html")

modules/plugins/views.py
import os
import shutil

from django.shortcuts import render, redirect

from modules.plugins.models import PluginsList
import asyncio


# Create your views here.
async def run(cmd):
    print(cmd)
    proc = await asyncio.create_subprocess_shell(
        cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE)
    stdout, stderr = await proc.communicate()
    print(f'[{cmd!r} exited with {proc.returncode}]')
    utf = 'utf-8'
    status = 'ignore'
    if stdout:
        # print(f'[stdout]\n{stdout.decode(utf,status)}')
        return proc.returncode
    if stderr:
        # print(f'[stderr]\n{stderr.decode(utf, status)}')
        return proc.returncode


def index(request):
    # operator
    # make any.properties file
    files_header = ["Name", "File Name", "Status", "Compilation", "Actions"]
    records = PluginsList.objects.all().values()
    return render(request, "plugins/index.html", {
        "headers": files_header,
        "records": records
    })


def handle_uploaded_file(f):
    with open('./plugins/' + f.name, 'wb') as destination:
        for chunk in f.chunks():
            destination.write(chunk)
    return destination.name


def delete_uploaded_file(f,c):
    path = './plugins/' + f
    class_path = './plugins/' + c
    if os.path.isfile(path):
        os.remove(path)
    if os.path.isfile(class_path):
        os.remove(class_path)


def delete_plugin(request, id):
    record = PluginsList.objects.get(id=id)
    delete_uploaded_file(record.filename, record.classfile)
    PluginsList.objects.get(id=id).delete()
    return redirect(index)


def uploadPlugins(request):
    if request.method == 'POST':
        name = request.POST['name']
        filename = request.FILES['file'].name
        path = handle_uploaded_file(request.FILES['file'])  # path from masc core shall be added
        data = PluginsList(name=name, filename=filename, path=path);
        data.save()
        return render(request, 'plugins/thanks.html')
    # list_of_operators = ["StringOperator","ByteOperator", "InterprocOperator", "Flexible", "IntOperator"]
    return render(request, "plugins/upload.html")


def compile_class(request, id):
    record = PluginsList.objects.get(id=id)
    status_code = asyncio.run(
         run('javac -cp ./modules/static/properties/app-all.jar ./plugins/'+record.filename))
    print(status_code)
    if status_code == None:
        record.compilation = 'true'
        record.classfile = record.filename.split('.')[0]+'.class'
    record.save()
    return redirect(index)


def update_status(request, id):
    record = PluginsList.objects.get(id=id)
    if record.status == 'active':
        if os.path.isfile('./plugins/'+record.classfile):
            shutil.move('./plugins/'+record.classfile,'./plugins-inactive/'+record.classfile)
        record.status = 'inactive'
    else:
        if os.path.isfile('./plugins-inactive/' + record.classfile):
            shutil.move('./plugins-inactive/' + record.classfile,'./plugins/' + record.classfile)
        record.status = 'active'
    record.save()
    return redirect(index)

modules/toolprofile/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

# Create your views here.
def index(request):
    # operator
    # make any.properties file
    return render(request, "tool-profile/index.html")

modules/templates/masc-engine/engine-details.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="container pb-2 pt-4">
    <div class="row">
        <div class="col-xl-9 col-lg-9">
            <h2 class="title">⚡️ MASC Engine</h2>
            <div>
                <span>
                    Mutate your code and analysis the result
                </span>
            </div>
        </div>
    </div>

    <div class="container mt-4">
        <div class="row">
            <div class="col-lg-12 col-xl-12">
                <d-card class="card">
                    <div class="p-4">
                        <form class="mt-3 mb-3" action="history" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-8 col-xl-8">
                                    <div class="form-group">
                                        <label for="fileElements"><b><i>File Contents</i></b></label>
                                        <textarea class="form-control" id="fileElements" rows="18"
                                                  name="content">{{ content }}</textarea>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-xl-4">
                                    <div class="form-group">
                                        <label for="scope">Selected Scope</label>
                                        <input type="text" class="form-control" id="scope"
                                               name="scope"
                                               aria-describedby="selectedScope" value="{{ scope }}">
                                    </div>
                                    <div class="form-group">
                                        <label for="filename">Property File Name</label>
                                        <input type="text" class="form-control" id="filename" name="file_name"
                                               aria-describedby="Property File Name" value="{{ filename }}">
                                    </div>
                                    <br>
                                     <div class="form-group">
                                        <label for="appName">App Name</label>
                                        <input type="text" class="form-control" id="appName" name="appName"
                                               aria-describedby="Enter App Name">
                                    </div>
                                    <div class="form-group">
                                        <label for="source"><b>Upload Source Code Zip</b></label>
                                        <input type="file" accept=".zip,.rar,.7zip" class="form-control" id="source" name="sourcecode"
                                               aria-describedby="Upload Zip File" required>
                                    </div>
                                    <div class="d-flex justify-content-center align-items-center">
                                        <button type="submit" class="btn btn-warning mt-3">Upload</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </d-card>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

modules/templates/masc-engine/engine.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="container pb-2 pt-4">
    <div class="row">
        <div class="col-xl-9 col-lg-9">
            <h2 class="title">⚡️ MASC Engine</h2>
            <div>
            <span>
                Mutate your code and analysis the result
            </span>
            </div>
        </div>
        <div class="col-xl-3 col-lg-3 pt-4">
            <div class="d-flex justify-content-end align-items-end">
                <a href="history" class="btn btn-primary">⏲️ Current Status</a>
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-xl-12 col-lg-12">
            <form method="post" action="">
                {% csrf_token %}
                <div class="row">
                    <div class="col-xl-12 col-lg-12">
                        <div class="form-group mt-4">
                            <label for="scopes"><h5>Select Scope</h5>
                            </label>
                            <select class="form-control" id="scopes"
                                    name="scopes">
                                {% for scope in scopes %}
                                <option>
                                    {{ scope }}
                                </option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group mt-4">
                            <label for="exampleFormControlSelectProperties"><h5>Select Properties File</h5>
                            </label>
                            <select class="form-control" id="exampleFormControlSelectProperties"
                                    name="properties">
                                {% for file in properties_file %}
                                <option>
                                    {{ file.filename }}
                                </option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="row mt-3">
                            <div class="d-flex justify-content-center align-items-center">
                                <button type="submit" class="btn btn-warning"><b>Submit Configurations</b></button>
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="d-flex justify-content-center align-items-center">
                                <a href="/properties/upload" class="btn btn-primary"><b>Create Configurations</b></a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

modules/templates/masc-engine/history.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="container pb-2 pt-4">
    <div class="row">
        <div class="col-xl-10 col-lg-10">
            <h2 class="title">⏲️ MASC Engine Status</h2>
            <div>
            <span>
                Status of current and previously ran processes
            </span>
            </div>
        </div>
        <div class="col-xl-2 col-lg-2 pt-4">
            <!--        <div class="d-flex justify-content-end align-items-end">-->
            <!--            <button class="btn btn-primary">Custom Operator</button>-->
            <!--        </div>-->
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-xl-12 col-lg-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                        <tr class="table-dark">
                            {% for header in custome_operator_headers %}
                            <th scope="col">{{ header }}</th>
                            {% endfor %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for record in records %}
                        <tr>
                            <th scope="row">{{ record.id }}</th>
                            <td scope="row">{{ record.scope }}</td>
                            <td scope="row">{{ record.properties_name }}</td>
                            <td scope="row">{{ record.source_code.appName }}</td>
                            <td scope="row">
                                {% if record.status == 'running' %}
                                <span class="badge bg-warning">{{ record.status }}</span>
                                {% elif record.status == 'failed' %}
                                <span class="badge bg-danger">{{ record.status }}</span>
                                {% elif record.status == 'completed' %}
                                <span class="badge bg-success">{{ record.status }}</span>
                                {% endif %}
                            </td>
                            <td>
                                <!--                                <a class="btn btn-primary" href="#">Details</a>-->
                                <a class="btn btn-danger"
                                   href="{% url 'MascEngine:deleteCode' id=record.source_code.id name=record.source_code.appName %}">
                                    {% load bootstrap_icons %}

                                    {% bs_icon 'trash' color='white' %}
                                </a>
                                {% if record.status == 'completed' %}
                                <a class="btn btn-success" href="{% url 'MascEngine:download' app_name=record.source_code.appName %}">
                                    {% bs_icon 'download' color='white' %}
                                </a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}